package hostrunner

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	hub "github.com/termipod/hub"
)

// TestCodexConfigTOML_WireShape pins the literal bytes the codex
// materializer emits. Two reasons we hard-pin instead of "looks
// roughly right":
//
//  1. The format is the integration contract with codex's parser. A
//     stray comma, a renamed key, or an unexpected blank line is the
//     kind of regression no integration test catches until a real
//     spawn fails.
//  2. The hub URL and token flow through with TOML escaping. A
//     future change that swaps in a different stringer must continue
//     to escape backslash, double quote, and control bytes the way
//     this fixture asserts.
func TestCodexConfigTOML_WireShape(t *testing.T) {
	t.Setenv("TERMIPOD_CODEX_APPROVAL_POLICY", "")
	got := codexConfigTOML(hub.MCPServerName, "https://hub.example/mcp/", "tok-abc123")
	want := "" +
		"# Generated by termipod host-runner. Re-spawning overwrites this file.\n" +
		"approval_policy = \"never\"\n" +
		"\n" +
		"[mcp_servers." + hub.MCPServerName + "]\n" +
		"command = \"hub-mcp-bridge\"\n" +
		"\n" +
		"[mcp_servers." + hub.MCPServerName + ".env]\n" +
		"HUB_URL = \"https://hub.example/mcp/\"\n" +
		"HUB_TOKEN = \"tok-abc123\"\n"
	if got != want {
		t.Fatalf("codex config.toml mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestCodexApprovalPolicy_Override pins the env-override contract.
// Operators who want codex's local gates back set
// TERMIPOD_CODEX_APPROVAL_POLICY to one of the codex-recognized
// values; anything unrecognized (including the upstream-deprecated
// "on-failure") falls back to the safe default rather than failing
// the spawn.
func TestCodexApprovalPolicy_Override(t *testing.T) {
	cases := []struct {
		env  string
		want string
	}{
		{"", "never"},
		{"never", "never"},
		{"on-request", "on-request"},
		{"untrusted", "untrusted"},
		{"NEVER", "never"},                // case-insensitive
		{"  on-request  ", "on-request"},  // trim
		{"on-failure", "never"},           // deprecated upstream → coerced
		{"bogus", "never"},                // unknown → coerced
	}
	for _, tc := range cases {
		t.Setenv("TERMIPOD_CODEX_APPROVAL_POLICY", tc.env)
		if got := codexApprovalPolicy(); got != tc.want {
			t.Errorf("env=%q: codexApprovalPolicy() = %q; want %q", tc.env, got, tc.want)
		}
	}
}

// TestTomlString covers the escape behaviour the wire-shape test
// can't easily reach. URL/token values that contain a backslash,
// double quote, or control byte must round-trip through TOML's
// basic-string escapes; otherwise codex either refuses the config
// or — worse — parses a different string than we wrote.
func TestTomlString(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"plain", `"plain"`},
		{`a"b`, `"a\"b"`},
		{`a\b`, `"a\\b"`},
		{"with\ttab", `"with\ttab"`},
		{"with\nnewline", `"with\nnewline"`},
		{"with\rcr", `"with\rcr"`},
		{"\x00ctrl", "\"\\u0000ctrl\""},
		{"", `""`},
	}
	for _, tc := range cases {
		if got := tomlString(tc.in); got != tc.want {
			t.Errorf("tomlString(%q) = %s; want %s", tc.in, got, tc.want)
		}
	}
}

// TestWriteCodexMCPConfig_WritesConfig pins the file-system shape:
// .codex/config.toml at 0o600 inside the workdir, with the TOML the
// wire-shape test asserts on. Used by slice 6's spawn template
// (which sets CODEX_HOME=<workdir>/.codex so codex picks up the
// project-scoped config without consulting its trusted-projects
// list).
func TestWriteCodexMCPConfig_WritesConfig(t *testing.T) {
	dir := t.TempDir()
	if err := writeCodexMCPConfig(dir, "https://hub.example/mcp/", "tok-1"); err != nil {
		t.Fatalf("writeCodexMCPConfig: %v", err)
	}
	target := filepath.Join(dir, ".codex", "config.toml")
	info, err := os.Stat(target)
	if err != nil {
		t.Fatalf("stat config.toml: %v", err)
	}
	if mode := info.Mode().Perm(); mode != 0o600 {
		t.Errorf("config.toml perms = %o; want 0600 (token is in cleartext)", mode)
	}
	body, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("read config.toml: %v", err)
	}
	if !strings.Contains(string(body), `HUB_TOKEN = "tok-1"`) {
		t.Errorf("config.toml missing HUB_TOKEN line:\n%s", body)
	}
	if !strings.Contains(string(body), `[mcp_servers.`+hub.MCPServerName+`.env]`) {
		t.Errorf("config.toml missing env stanza:\n%s", body)
	}
}

// TestWriteCodexMCPConfig_CopiesAuthJSON pins the auth-bridging
// behaviour: when the user's $CODEX_HOME (or $HOME/.codex) contains
// auth.json, writeCodexMCPConfig copies it into the spawn-scoped
// CODEX_HOME so codex can authenticate the same way it does in a
// terminal. Without this, redirecting CODEX_HOME loses access to the
// user's API-key / login credentials and codex fails with
// "401 Unauthorized" on its OpenAI websocket.
func TestWriteCodexMCPConfig_CopiesAuthJSON(t *testing.T) {
	// Stage a fake "user" CODEX_HOME with an auth.json.
	userHome := t.TempDir()
	userCodex := filepath.Join(userHome, ".codex")
	if err := os.MkdirAll(userCodex, 0o700); err != nil {
		t.Fatalf("mkdir user codex: %v", err)
	}
	authBody := []byte(`{"OPENAI_API_KEY":"sk-test-redacted"}`)
	if err := os.WriteFile(filepath.Join(userCodex, "auth.json"), authBody, 0o600); err != nil {
		t.Fatalf("write user auth.json: %v", err)
	}
	t.Setenv("CODEX_HOME", userCodex)

	dir := t.TempDir()
	if err := writeCodexMCPConfig(dir, "https://hub.example/mcp/", "tok-1"); err != nil {
		t.Fatalf("writeCodexMCPConfig: %v", err)
	}

	target := filepath.Join(dir, ".codex", "auth.json")
	info, err := os.Stat(target)
	if err != nil {
		t.Fatalf("auth.json not copied into spawn CODEX_HOME: %v", err)
	}
	if mode := info.Mode().Perm(); mode != 0o600 {
		t.Errorf("auth.json perms = %o; want 0600 (token is sensitive)", mode)
	}
	got, _ := os.ReadFile(target)
	if string(got) != string(authBody) {
		t.Errorf("auth.json content not preserved\n got: %s\nwant: %s", got, authBody)
	}
}

// TestWriteCodexMCPConfig_NoAuthIsBestEffort pins the fallback: if
// the user has no auth.json (e.g. headless deploy with $OPENAI_API_KEY
// in env), the spawn still writes config.toml and reports success —
// auth.json is purely additive.
func TestWriteCodexMCPConfig_NoAuthIsBestEffort(t *testing.T) {
	// Point at a CODEX_HOME with no auth.json present.
	emptyHome := t.TempDir()
	t.Setenv("CODEX_HOME", emptyHome)

	dir := t.TempDir()
	if err := writeCodexMCPConfig(dir, "https://hub.example/mcp/", "tok-1"); err != nil {
		t.Fatalf("writeCodexMCPConfig must not fail when auth.json is absent: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".codex", "config.toml")); err != nil {
		t.Errorf("config.toml still expected: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".codex", "auth.json")); !os.IsNotExist(err) {
		t.Errorf("auth.json should NOT exist when source is missing; err = %v", err)
	}
}

// TestWriteMCPConfigForFamily_DispatchesByKind pins the per-family
// dispatch: family=codex picks the TOML path, anything else falls
// back to .mcp.json. This is the contract launch_m2.go relies on to
// keep claude (and everything else) on the JSON shape unchanged
// while codex gets its own materializer.
func TestWriteMCPConfigForFamily_DispatchesByKind(t *testing.T) {
	t.Run("codex writes config.toml", func(t *testing.T) {
		dir := t.TempDir()
		if err := writeMCPConfigForFamily("codex", dir, "u", "t"); err != nil {
			t.Fatalf("err: %v", err)
		}
		if _, err := os.Stat(filepath.Join(dir, ".codex", "config.toml")); err != nil {
			t.Errorf(".codex/config.toml missing: %v", err)
		}
		if _, err := os.Stat(filepath.Join(dir, ".mcp.json")); !os.IsNotExist(err) {
			t.Errorf(".mcp.json should NOT exist for codex spawns; got err = %v", err)
		}
	})
	t.Run("claude-code writes .mcp.json", func(t *testing.T) {
		dir := t.TempDir()
		if err := writeMCPConfigForFamily("claude-code", dir, "u", "t"); err != nil {
			t.Fatalf("err: %v", err)
		}
		if _, err := os.Stat(filepath.Join(dir, ".mcp.json")); err != nil {
			t.Errorf(".mcp.json missing: %v", err)
		}
		if _, err := os.Stat(filepath.Join(dir, ".codex", "config.toml")); !os.IsNotExist(err) {
			t.Errorf(".codex/config.toml should NOT exist for claude spawns")
		}
	})
	t.Run("unknown family falls back to .mcp.json", func(t *testing.T) {
		dir := t.TempDir()
		if err := writeMCPConfigForFamily("future-engine", dir, "u", "t"); err != nil {
			t.Fatalf("err: %v", err)
		}
		if _, err := os.Stat(filepath.Join(dir, ".mcp.json")); err != nil {
			t.Errorf("fallback .mcp.json missing: %v", err)
		}
	})
}
