/// Cross-language conformance for the resume-recipe reader (vision-parity L3b).
///
/// The hub resolves "how do I reattach to this engine's session" in Go; the
/// Companion has to answer it in TypeScript to rebind a local session after an
/// app restart. That is two implementations of one table, which is the shape
/// that drifts quietly — and here the failure is worse than usual, because
/// recipes.yaml says so itself: *a wrong resume command does not error, it
/// silently starts a fresh conversation.* A drifted reader loses the
/// director's context and reports success.
///
/// So this file does not check that the reader is reasonable. It replays the
/// hub's own corpus — every `engine_argv` case, every `session_ref_validation`
/// case, every `family_plans` case — and requires the same answer. The corpus
/// is generated by `hub/internal/resumerecipes/fixture_test.go`, which fails
/// when stale, so a table edit cannot land without updating what this compares
/// against.
///
/// Reading the hub's testdata directly is the point, exactly as in
/// `frameprofile/parity.test.ts`: copying the corpus into `desktop/` would make
/// conformance a matter of remembering to re-copy.
///
/// `shell_quote` is the one section deliberately skipped — see resumerecipes.ts
/// for why we have no shell string to quote into.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  engineByID,
  engineResumeArgv,
  newSessionID,
  newSessionPath,
  parseResumeTable,
  resumeArgv,
  resumeSplice,
  type ResumeTable,
  type SessionRef,
} from './resumerecipes.ts';

// src/localagent → src → electron → desktop → repo root.
const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..');
const FIXTURE_PATH = join(REPO_ROOT, 'hub', 'internal', 'resumerecipes', 'testdata', 'resume_recipes_fixture.json');
const ARTIFACT_PATH = join(REPO_ROOT, 'desktop', 'electron', 'resources', 'resume_recipes.generated.json');

interface EngineArgvCase {
  engine: string;
  bin: string;
  goos: string;
  ref_kind: string;
  ref_value: string;
  argv?: string[];
  error?: string;
  verified: string;
}

interface RefValidationCase {
  kind: string;
  value: string;
  valid: boolean;
  why: string;
}

interface FamilyPlanCase {
  family: string;
  mechanism: string;
  ref_kind: string;
  ref_value: string;
  engine?: string;
  argv?: string[];
  dedupe_key?: string;
  error?: string;
}

interface Fixture {
  version: number;
  engine_argv: EngineArgvCase[];
  session_ref_validation: RefValidationCase[];
  family_plans: FamilyPlanCase[];
}

const fixture = JSON.parse(readFileSync(FIXTURE_PATH, 'utf-8')) as Fixture;
const table: ResumeTable = parseResumeTable(readFileSync(ARTIFACT_PATH, 'utf-8'));

/// The corpus records Go's GOOS; node reports `process.platform`. They agree on
/// every value we use except Windows, which is the one that actually selects a
/// different binary — so the mapping is a table, not a cast.
function platformForGoos(goos: string): string {
  return goos === 'windows' ? 'win32' : goos;
}

/// Build the ref the case describes WITHOUT validating it. The argv cases use
/// sentinel values (`SESSION`, `/abs/session.jsonl`) whose validity is the
/// separate section's job; conflating the two would let a validation bug hide
/// as an argv bug.
function refOf(c: EngineArgvCase): SessionRef {
  return { kind: c.ref_kind as SessionRef['kind'], value: c.ref_value };
}

test('the table artifact and the fixture were generated from the same recipes.yaml', () => {
  // Both files are generated from one source; if a regeneration only touched
  // one, every comparison below is against a table that no longer matches the
  // corpus. Version is the cheap tripwire the corpus already carries.
  assert.equal(table.version, fixture.version,
    'resume_recipes.generated.json and resume_recipes_fixture.json disagree on version — ' +
    'regenerate both from hub/internal/resumerecipes');
});

test('engine_argv: every case in the hub corpus', () => {
  assert.ok(fixture.engine_argv.length > 0, 'corpus is empty');
  let checked = 0;
  for (const c of fixture.engine_argv) {
    const engine = engineByID(table, c.engine);
    assert.ok(engine !== undefined, `engine ${c.engine} missing from the generated table`);
    const got = engineResumeArgv(engine, refOf(c), platformForGoos(c.goos));
    const label = `${c.engine}/${c.goos}/${c.ref_kind}`;

    if (c.error !== undefined && c.error !== '') {
      assert.equal(got.ok, false, `${label}: expected error ${c.error}, got argv`);
      if (!got.ok) assert.equal(got.error, c.error, `${label}: wrong error`);
    } else {
      assert.equal(got.ok, true, `${label}: expected argv, got error`);
      if (got.ok) assert.deepEqual(got.argv, c.argv, `${label}: argv mismatch`);
    }
    checked += 1;
  }
  // The loop asserting nothing when the corpus fails to parse into cases is the
  // classic silent pass; pin the count the corpus actually has.
  assert.equal(checked, fixture.engine_argv.length);
});

test('engine_argv: the bin the corpus names is the bin we would run', () => {
  // `binFor` is exercised implicitly above only when a windows_bin differs.
  // State it directly so a reader can see the platform rule is honoured rather
  // than coincidentally unexercised.
  for (const c of fixture.engine_argv) {
    if (c.argv === undefined) continue;
    assert.equal(c.argv[0], c.bin, `corpus self-check: ${c.engine}/${c.goos}`);
  }
});

test('session_ref_validation: every case, including the UTF-8 byte cases', () => {
  let checked = 0;
  for (const c of fixture.session_ref_validation) {
    const got = c.kind === 'path' ? newSessionPath(c.value) : newSessionID(c.value);
    assert.equal(got !== null, c.valid, `${c.kind}: ${c.why}`);
    if (got !== null) assert.equal(got.value, c.value);
    checked += 1;
  }
  assert.equal(checked, fixture.session_ref_validation.length);
});

test('session_ref_validation: the corpus really does separate bytes from string units', () => {
  // A guard against the corpus silently losing the case that makes the byte
  // rule observable. Without a value whose UTF-8 length differs from its UTF-16
  // length, `String.length` would pass every case above and the reader would
  // still be wrong for any non-ASCII session id.
  const divergent = fixture.session_ref_validation.filter(
    (c) => c.kind === 'id' && new TextEncoder().encode(c.value).length !== c.value.length,
  );
  assert.ok(divergent.length > 0,
    'no case where UTF-8 bytes differ from JS string units; the byte-length rule is untested');
});

test('family_plans: every case in the hub corpus', () => {
  let checked = 0;
  for (const c of fixture.family_plans) {
    // family_plans is recorded on linux; the corpus carries no goos column
    // because no family row is platform-dependent.
    const got = resumeArgv(table, c.family, { kind: c.ref_kind as SessionRef['kind'], value: c.ref_value }, 'linux');
    if (c.error !== undefined && c.error !== '') {
      assert.equal(got.ok, false, `${c.family}: expected error ${c.error}`);
      if (!got.ok) assert.equal(got.error, c.error, `${c.family}: wrong error`);
    } else {
      assert.equal(got.ok, true, `${c.family}: expected argv`);
      if (got.ok) {
        assert.deepEqual(got.argv, c.argv, `${c.family}: argv mismatch`);
        assert.equal(got.engine, c.engine, `${c.family}: engine mismatch`);
      }
    }
    checked += 1;
  }
  assert.equal(checked, fixture.family_plans.length);
});

test('family_plans: the corpus covers both a resuming and a non-resuming family', () => {
  // Otherwise "every case passes" is satisfied by a corpus that only ever
  // exercises one branch of the mechanism check.
  const argvFamilies = fixture.family_plans.filter((c) => c.error === undefined);
  const otherFamilies = fixture.family_plans.filter((c) => c.error === 'not_argv_resume');
  assert.ok(argvFamilies.length > 0, 'no argv-resuming family in the corpus');
  assert.ok(otherFamilies.length > 0, 'no non-argv family in the corpus');
});

// ── the splice, which is ours and has no Go counterpart ────────────────────

test('resumeSplice drops the binary and keeps the flag tokens', () => {
  const ref = newSessionID('abc-123');
  assert.ok(ref !== null);
  const got = resumeSplice(table, 'claude-code', ref, 'linux');
  assert.equal(got.ok, true);
  if (got.ok) {
    assert.deepEqual(got.tokens, ['--resume', 'abc-123']);
    // The service appends these to a launch argv that already names the binary.
    // If the bin ever survived the slice, the child would be spawned as
    // `claude claude --resume …`, which claude reads as a prompt.
    assert.ok(!got.tokens.includes('claude'), 'the binary leaked into the splice');
  }
});

test('resumeSplice refuses a family that does not resume by argv', () => {
  const ref = newSessionID('abc-123');
  assert.ok(ref !== null);
  const got = resumeSplice(table, 'codex', ref, 'linux');
  assert.equal(got.ok, false);
  if (!got.ok) assert.equal(got.error, 'not_argv_resume');
});

test('resumeSplice refuses an unknown family rather than guessing a default', () => {
  const ref = newSessionID('abc-123');
  assert.ok(ref !== null);
  const got = resumeSplice(table, 'no-such-family', ref, 'linux');
  assert.equal(got.ok, false);
  if (!got.ok) assert.equal(got.error, 'unknown_family');
});

test('a flag_equals engine produces two tokens, not three', () => {
  // The style distinction is load-bearing: `--resume=X` as a pair would be
  // `--resume= X`, which every one of these CLIs reads as an empty value.
  const engine = engineByID(table, 'copilot');
  assert.ok(engine !== undefined);
  const got = engineResumeArgv(engine, { kind: 'id', value: 'abc-123' }, 'linux');
  assert.equal(got.ok, true);
  if (got.ok) assert.deepEqual(got.argv, ['copilot', '--resume=abc-123']);
});

// ── parse guards ───────────────────────────────────────────────────────────

test('parseResumeTable rejects a truncated artifact at load, not at rebind', () => {
  assert.throws(() => parseResumeTable('{"version":1,"engines":[]}'), /engines or families|empty/);
  assert.throws(() => parseResumeTable('{"version":1,"engines":[],"families":[]}'), /empty/);
  assert.throws(() => parseResumeTable('null'), /not an object/);
});

test('the shipped artifact carries the claude row rebind depends on', () => {
  const claude = engineByID(table, 'claude');
  assert.ok(claude !== undefined, 'no claude engine row');
  assert.equal(claude.style, 'flag_pair');
  assert.equal(claude.token, '--resume');
  assert.deepEqual(claude.ref_kinds, ['id']);
});
