/// Cross-language parity for the frame-profile interpreter. Run with
/// `node --test`.
///
/// The hub interprets ADR-010 frame profiles in Go; the Companion has to
/// interpret the same rules in TypeScript to run agents locally (vision-parity
/// L3/L4). Two implementations of one rule language is the shape that drifts
/// quietly: both stay green, both stay plausible, and the transcripts stop
/// agreeing on some engine nobody is looking at.
///
/// So this file does not check that the TypeScript interpreter is *reasonable*.
/// It checks that it produces, byte for byte, what the Go one produced — over
/// the hub's own corpus, through the hub's own profiles, plus a set of
/// expression cases aimed at the grammar's corners. The expected values are
/// generated by `hub/internal/hostrunner/profile_fixture_test.go`, which fails
/// when they are stale, so a rule edit on the Go side cannot land without
/// updating what this file compares against.
///
/// Reading the hub's testdata directly is the point. Copying the corpus into
/// `desktop/` would make parity a matter of remembering to re-copy — which is
/// precisely the discipline this arrangement exists to replace.
///
/// The profile arrives as JSON, marshalled from the very structs the hub's
/// loader fills from YAML, rather than being parsed from `agent_families.yaml`
/// here — the Electron main bundle has no YAML parser and does not need one to
/// answer this question. A field that fails to cross that boundary (a `yaml:`
/// tag with no `json:` twin, say) is not invisible: the TS interpreter cannot
/// apply what it never received, so its events stop matching the recorded ones
/// and this file fails.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { applyProfile } from './translate.ts';
import { evalExpr } from './eval.ts';
import type { EmittedEvent, FrameProfile, Scope } from './types.ts';

// src/frameprofile → src → electron → desktop → repo root.
const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..');
const PROFILE_TESTDATA = join(REPO_ROOT, 'hub', 'internal', 'hostrunner', 'testdata', 'profiles');

/// Families whose profiles both interpreters must agree on, paired with the
/// corpus directory. The names differ for gemini (family `gemini-cli`, dir
/// `gemini`), which is why this is a table and not a string.
const FAMILIES = [
  { family: 'claude-code', dir: 'claude-code' },
  { family: 'codex', dir: 'codex' },
  { family: 'gemini-cli', dir: 'gemini' },
];

interface ParityFixture {
  family: string;
  corpus: string;
  profile: FrameProfile;
  events: EmittedEvent[][];
}

interface GrammarFixture {
  scopes: Record<string, Record<string, unknown>>;
  cases: { name: string; expr: string; inner: string; outer: string; result: unknown }[];
}

interface TranslateCase {
  name: string;
  why: string;
  profile: FrameProfile;
  frame: Record<string, unknown>;
  events: EmittedEvent[];
}

function readJson<T>(...parts: string[]): T {
  return JSON.parse(readFileSync(join(PROFILE_TESTDATA, ...parts), 'utf-8')) as T;
}

/// Parse a corpus file the way the Go `readCorpus` helper does: trim each line,
/// skip blanks and `#` comments, decode the rest. Any drift here shortens the
/// frame list, which the count assertion below catches — a parser that silently
/// tested fewer frames would be worse than one that failed.
function readCorpus(dir: string): Record<string, unknown>[] {
  const raw = readFileSync(join(PROFILE_TESTDATA, dir, 'corpus.jsonl'), 'utf-8');
  const frames: Record<string, unknown>[] = [];
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (trimmed === '' || trimmed.startsWith('#')) continue;
    frames.push(JSON.parse(trimmed) as Record<string, unknown>);
  }
  return frames;
}

for (const { family, dir } of FAMILIES) {
  test(`${family}: every corpus frame translates as the Go interpreter does`, () => {
    const fixture = readJson<ParityFixture>(dir, 'parity.json');
    const corpus = readCorpus(dir);

    assert.equal(fixture.family, family, 'fixture is for a different family');
    assert.ok(corpus.length > 0, `corpus for ${family} is empty`);
    // The fixture holds no frames — only results, indexed by corpus line. If
    // the two lengths disagree, the two sides are not looking at the same
    // corpus and every per-frame comparison below is meaningless.
    assert.equal(
      corpus.length,
      fixture.events.length,
      `read ${corpus.length} frames but the Go fixture recorded ` +
        `${fixture.events.length}. Regenerate: go test ./internal/hostrunner/ ` +
        `-run Fixture -update-frame-fixture`,
    );

    corpus.forEach((frame, i) => {
      const got = applyProfile(frame, fixture.profile);
      assert.deepStrictEqual(
        got,
        fixture.events[i],
        `frame ${i} of ${dir}/corpus.jsonl translated differently:\n` +
          `${JSON.stringify(frame)}`,
      );
    });
  });
}

test('every rule shape translates as the Go interpreter does', () => {
  // The corpus proves the ports agree on what termipod ships. These are the
  // parts of the rule language nothing ships yet — where a port drifts unseen
  // until an engine profile reaches for one.
  const cases = readJson<TranslateCase[]>('translate.json');
  assert.ok(cases.length > 0, 'translate fixture has no cases');

  for (const c of cases) {
    assert.deepStrictEqual(
      applyProfile(c.frame, c.profile),
      c.events,
      `${c.name} — ${c.why}`,
    );
  }
});

test('the grammar resolves every corner case as the Go evaluator does', () => {
  const fixture = readJson<GrammarFixture>('grammar.json');
  assert.ok(fixture.cases.length > 0, 'grammar fixture has no cases');

  for (const c of fixture.cases) {
    // An empty scope name is the nil scope — what `$$.` sees outside a
    // for_each. Go's map lookup yields a nil map there; ours yields null.
    const inner: Scope = fixture.scopes[c.inner] ?? null;
    const outer: Scope = fixture.scopes[c.outer] ?? null;
    assert.deepStrictEqual(
      evalExpr(c.expr, inner, outer),
      c.result,
      `${c.name}: ${c.expr}`,
    );
  }
});

test('the grammar fixture covers the corners the corpus cannot reach', () => {
  const fixture = readJson<GrammarFixture>('grammar.json');
  const names = new Set(fixture.cases.map((c) => c.name.split('/')[0]));
  // Naming the groups here is what makes a silently-shrinking fixture visible.
  // Deleting a case group on the Go side regenerates cleanly and would
  // otherwise leave this suite passing over less.
  for (const group of [
    'path',
    'index',
    'scope',
    'js-trap',
    'coalesce',
    'literal',
    'present',
    'absent',
    'nonempty',
    'whitespace',
    'empty',
  ]) {
    assert.ok(names.has(group), `grammar fixture lost its "${group}" cases`);
  }
});
