#!/usr/bin/env node
// build.mjs — TermiPod shared design-token pipeline (WS1, implements ADR-051).
//
// The DTCG `tokens.json` in this directory is the neutral source of truth for
// both clients. This zero-dependency emitter:
//   * writes `build/tokens.css` (CSS custom properties) for the web/desktop
//     client, and
//   * verifies the Flutter mirror (lib/theme/tokens.dart + design_colors.dart)
//     carries exactly these values, so the two clients cannot drift.
//
// The Flutter files stay hand-authored (they carry the ADR-047 guidance docs);
// this script makes the JSON authoritative-by-enforcement instead of
// regenerating them. Open Question 1 of docs/plans/desktop-control-plane.md is
// resolved this way. A Style-Dictionary emitter could replace this later — the
// input is standard DTCG — but a ~60-value set doesn't justify the dependency.
//
// Usage:
//   node design-tokens/build.mjs           # regenerate build/tokens.css
//   node design-tokens/build.mjs --check    # verify Dart parity + CSS is current (CI); exit 1 on drift
//
// No external dependencies — Node >= 18 (uses node:fs, node:path, node:url).

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..');
const CHECK = process.argv.includes('--check');

// group key in tokens.json -> { Dart file, Dart class, kind, CSS prefix }
const GROUPS = {
  spacing: { file: 'lib/theme/tokens.dart', cls: 'Spacing', kind: 'dimension', css: 'spacing' },
  radius: { file: 'lib/theme/tokens.dart', cls: 'Radii', kind: 'dimension', css: 'radius' },
  fontSize: { file: 'lib/theme/tokens.dart', cls: 'FontSizes', kind: 'dimension', css: 'font-size' },
  iconSize: { file: 'lib/theme/tokens.dart', cls: 'IconSizes', kind: 'dimension', css: 'icon-size' },
  color: { file: 'lib/theme/design_colors.dart', cls: 'DesignColors', kind: 'color', css: 'color' },
};

const tokens = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'));
const errors = [];

// ---- helpers ----------------------------------------------------------------

// camelCase / sNN token name -> kebab-case CSS segment (s16 -> s16, primaryDark
// -> primary-dark, onWarningContainerLight -> on-warning-container-light).
const kebab = (name) => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

// tokens under a group, skipping DTCG metadata ($-prefixed keys).
const entries = (group) =>
  Object.entries(tokens[group]).filter(([k]) => !k.startsWith('$'));

// Extract a single Dart class body from a source file.
function dartClassBody(src, cls) {
  const start = src.indexOf(`class ${cls} `);
  if (start === -1) return null;
  const open = src.indexOf('{', start);
  let depth = 0;
  for (let i = open; i < src.length; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') {
      depth--;
      if (depth === 0) return src.slice(open + 1, i);
    }
  }
  return null;
}

// ---- CSS emit ---------------------------------------------------------------

function buildCss() {
  const lines = [
    '/* AUTO-GENERATED by design-tokens/build.mjs from tokens.json — do not edit.',
    ' * Shared design tokens (ADR-047 / ADR-051). Regenerate: node design-tokens/build.mjs */',
    ':root {',
  ];
  for (const [group, meta] of Object.entries(GROUPS)) {
    lines.push(`  /* ${group} */`);
    for (const [name, tok] of entries(group)) {
      const v = tok.$value;
      const value = meta.kind === 'dimension' ? `${v}px` : String(v);
      lines.push(`  --${meta.css}-${kebab(name)}: ${value};`);
    }
  }
  lines.push('}', '');
  return lines.join('\n');
}

// ---- Dart parity check ------------------------------------------------------

function checkDart() {
  for (const [group, meta] of Object.entries(GROUPS)) {
    const src = readFileSync(join(repo, meta.file), 'utf8');
    const body = dartClassBody(src, meta.cls);
    if (body == null) {
      errors.push(`${meta.file}: class ${meta.cls} not found`);
      continue;
    }
    const jsonTokens = new Map(entries(group).map(([n, t]) => [n, t.$value]));
    const dart = new Map();

    if (meta.kind === 'color') {
      // static const NAME = Color(0xFFRRGGBB);
      const re = /static const (\w+)\s*=\s*Color\(0x([0-9A-Fa-f]{8})\)/g;
      let m;
      while ((m = re.exec(body))) {
        const hex8 = m[2].toUpperCase();
        if (!hex8.startsWith('FF')) {
          errors.push(`${meta.cls}.${m[1]}: non-opaque 0x${hex8} — tokens.json models opaque colors only`);
        }
        dart.set(m[1], `#${hex8.slice(2)}`);
      }
      for (const [n, want] of jsonTokens) {
        const got = dart.get(n);
        if (got === undefined) errors.push(`${meta.cls}.${n}: in tokens.json but missing in Dart`);
        else if (got.toUpperCase() !== String(want).toUpperCase())
          errors.push(`${meta.cls}.${n}: Dart ${got} != tokens.json ${want}`);
      }
      for (const n of dart.keys())
        if (!jsonTokens.has(n)) errors.push(`${meta.cls}.${n}: in Dart but missing from tokens.json`);
    } else {
      // static const double NAME = VALUE;  (ignore BorderRadius composites etc.)
      const re = /static const double (\w+)\s*=\s*([\d.]+)\s*;/g;
      let m;
      while ((m = re.exec(body))) dart.set(m[1], Number(m[2]));
      for (const [n, want] of jsonTokens) {
        const got = dart.get(n);
        if (got === undefined) errors.push(`${meta.cls}.${n}: in tokens.json but missing in Dart`);
        else if (got !== Number(want)) errors.push(`${meta.cls}.${n}: Dart ${got} != tokens.json ${want}`);
      }
      for (const n of dart.keys())
        if (!jsonTokens.has(n)) errors.push(`${meta.cls}.${n}: in Dart but missing from tokens.json`);
    }
  }
}

// ---- run --------------------------------------------------------------------

const cssPath = join(here, 'build', 'tokens.css');
const css = buildCss();

if (CHECK) {
  checkDart();
  let current = '';
  try { current = readFileSync(cssPath, 'utf8'); } catch { /* missing */ }
  if (current !== css) {
    errors.push('build/tokens.css is stale — run: node design-tokens/build.mjs');
  }
  if (errors.length) {
    console.error('design-tokens: FAIL');
    for (const e of errors) console.error('  - ' + e);
    process.exit(1);
  }
  console.log('design-tokens: clean (Dart mirror matches tokens.json; tokens.css current)');
} else {
  checkDart(); // surface drift on regen too, but still write
  writeFileSync(cssPath, css);
  console.log(`design-tokens: wrote ${cssPath} (${entries('color').length} colors + dimension scales)`);
  if (errors.length) {
    console.error('design-tokens: WARNING — Dart mirror drift:');
    for (const e of errors) console.error('  - ' + e);
    process.exit(1);
  }
}
