#!/usr/bin/env bash
# lint-glossary.sh — enforce docs/doc-spec.md §7 term-consistency
# rules against docs/reference/glossary.md.
#
# Four checks:
#   1. Glossary structure — every `### term` heading has a non-empty
#      definition line within the next 5 lines (no orphan headings).
#   2. Index integrity — every term cross-referenced in §12 of the
#      glossary resolves to an actual `### term` heading above it
#      (or to one of its known aliases).
#   3. Spelling-variant detection — for each canonical glossary
#      term, scan all docs for known-bad alternate spellings (the
#      `## Variant` lines below) and flag them as drift.
#   4. New-term gate — for docs touched in this PR, identify
#      project-specific terms that look load-bearing (bolded
#      occurrences of multi-word lowercase terms or schema-shaped
#      identifiers) and warn when they have no glossary entry.
#      Warning-level only at MVP scale; promotes to fail once the
#      first retroactive sweep clears the backlog.
#
# Run from repo root:   scripts/lint-glossary.sh
# CI usage:             added as a step in .github/workflows/ci.yml
#
# Exits 0 on clean, 1 on any check 1-3 failure. Check 4 emits WARN
# lines that don't fail the build (yet).

set -u

cd "$(dirname "$0")/.."

GLOSSARY="docs/reference/glossary.md"

if [[ ! -f "$GLOSSARY" ]]; then
  echo "FAIL [glossary-missing]: $GLOSSARY does not exist (doc-spec §7)"
  exit 1
fi

failed=0
warned=0

# --- Check 1: glossary structure ---
#
# Every `### name` heading should be followed by a definition line
# within 5 lines. Catches the "added the heading, forgot the body"
# regression.

awk '
/^### / {
  if (heading_line && !has_def) {
    printf "FAIL [orphan-heading]: %s:%d — %s has no definition body within 5 lines\n",
           FILENAME, heading_line, heading
    exit_code = 1
  }
  heading_line = NR
  heading = $0
  has_def = 0
  next
}
heading_line && NR <= heading_line + 5 && /^[A-Za-z*_`]/ {
  # First non-empty body line that looks like prose, bold, italic,
  # or code-fenced text. Anything starting with a letter or one of
  # the markdown emphasis sigils counts as a definition.
  has_def = 1
}
END {
  if (heading_line && !has_def) {
    printf "FAIL [orphan-heading]: %s:%d — %s has no definition body within 5 lines\n",
           FILENAME, heading_line, heading
    exit_code = 1
  }
  exit exit_code+0
}
' "$GLOSSARY"
if [[ $? -ne 0 ]]; then failed=1; fi

# --- Check 2: §12 index integrity ---
#
# Every "**term**" called out in §12's confusion-pairs index must
# correspond to a `### term` heading earlier in the file. Otherwise
# §12 grows stale or points at terms that were renamed.

# Extract all `### name` heading slugs (lowercase, hyphenated form
# of the heading text). yaml-style anchors aren't auto-generated by
# our renderer; we treat the heading text itself as the slug.
declare -A canon_terms=()
while IFS= read -r line; do
  # `### hub session` -> `hub session`. Quoting the prefix is
  # mandatory: bare `${var#### }` parses as the `##` longest-match
  # operator followed by `## ` pattern and silently no-ops.
  term="${line#'### '}"
  # Strip a trailing parenthetical qualifier so `session
  # (unqualified)` registers under both the full heading and the
  # bare alias `session` for §12 lookups.
  short_term="${term%% (*}"
  if [[ -n "$term" ]]; then
    canon_terms["$term"]=1
  fi
  if [[ -n "$short_term" && "$short_term" != "$term" ]]; then
    canon_terms["$short_term"]=1
  fi
done < <(grep -E '^### ' "$GLOSSARY" || true)

# Find §12 in the file and check each bolded term in it has an entry.
# §12 is parsed as: lines after `## 12. Index` heading until the next
# `## ` heading.
in_index=0
while IFS= read -r line; do
  if [[ "$line" =~ ^##\ 12 ]]; then
    in_index=1
    continue
  fi
  if [[ $in_index -eq 1 && "$line" =~ ^##\ [0-9] ]]; then
    in_index=0
    continue
  fi
  if [[ $in_index -eq 1 ]]; then
    # Pull every `**term**` from the line.
    while IFS= read -r match; do
      [[ -z "$match" ]] && continue
      # Skip qualifying labels in parens like "(handler)" / "(CLI flag)".
      base="${match%% (*}"
      # Skip schema-shaped tokens (snake_case identifiers).
      if [[ "$base" =~ ^[a-z_]+$ && "$base" =~ _ ]]; then
        continue
      fi
      if [[ -z "${canon_terms[$base]+x}" ]]; then
        # Tolerate a few well-known aliases referenced in §12 that
        # canonicalise differently in their entry heading.
        case "$base" in
          session) ;; # alias for "session (unqualified)"
          *)
            echo "FAIL [stale-index]: §12 refers to '$base' but no '### $base' entry exists"
            failed=1
            ;;
        esac
      fi
    done < <(echo "$line" | grep -oE '\*\*[^*]+\*\*' | sed 's/\*\*//g')
  fi
done < "$GLOSSARY"

# --- Check 3: spelling-variant drift ---
#
# For each canonical term, look for known bad alternate spellings
# across the docs/ tree. The mapping below is the curated drift
# list — extend as new variants surface in retroactive sweeps.

declare -A variant_map=()
# Each line: "canonical=variant1|variant2|..."
# variants are case-sensitive fixed-string matches.
#
# Conservative on purpose: only list variants that are unambiguously
# wrong, never legitimate adjectival hyphenations or compound forms.
# For example, `frame profile` is canonical for the noun, but
# "frame-profile substrate" is grammatical English and stays
# unflagged. Add new variants here as retroactive sweeps expose
# real drift; resist the urge to flag every hyphen-space difference.
variant_map["hub session"]="Hub Session"
variant_map["host-runner"]="host runner"
variant_map["app-server"]="AppServer"
variant_map["stream-json"]="streamjson|stream json"

# Search across docs/ but skip the glossary itself, archive, and
# screens (which are layout sketches, not prose).
DOC_GLOB="docs"
EXCLUDES=(--exclude-dir=archive --exclude-dir=screens --exclude-dir=logo)

# find_prose_files: stable list of doc files to scan, excluding the
# directories check 1's glob already excluded.
mapfile -t prose_files < <(find "$DOC_GLOB" -type f -name '*.md' \
  -not -path '*/archive/*' \
  -not -path '*/screens/*' \
  -not -path '*/logo/*' | sort)

# scan_variant_in_file: emits FAIL lines for prose-context occurrences
# of $variant in $file. Skips:
#   - lines inside ``` fenced code blocks
#   - inline-backticked occurrences (`hostrunner`)
#   - path-like contexts (preceded or followed by /, ., or _)
#
# This is the bulk of the lint's signal-to-noise — without code-
# context filtering, every Go package import of `hostrunner` flags
# spuriously, drowning out the real prose drift.
scan_variant_in_file() {
  local file="$1" variant="$2" canon="$3"
  awk -v variant="$variant" -v canon="$canon" -v file="$file" '
    BEGIN { in_fence = 0; rc = 0 }
    {
      line = $0
      # Toggle fence state on lines starting with ``` (with or
      # without language tag). Lines inside the fence never count.
      if (line ~ /^[[:space:]]*```/) {
        in_fence = !in_fence
        next
      }
      if (in_fence) next
      # Strip inline-backticked spans so a `hostrunner` mention
      # inside prose like "the `hostrunner` package" doesnt match.
      stripped = line
      gsub(/`[^`]*`/, "", stripped)
      # Path / identifier context: a preceding or following char
      # in [/._] means the variant is part of a longer technical
      # token. Match only when surrounded by word boundaries.
      n = index(stripped, variant)
      while (n > 0) {
        before = (n > 1) ? substr(stripped, n-1, 1) : ""
        after = substr(stripped, n + length(variant), 1)
        if (before !~ /[\/._a-zA-Z0-9-]/ && after !~ /[\/._a-zA-Z0-9-]/) {
          # Allow only word-boundary-ish surroundings. The trailing
          # hyphen check matters: "host-runner" itself contains
          # "host runner" once we strip the hyphen — we add hyphen
          # to the negative class so the canonical form does not
          # self-match.
          printf "FAIL [variant-drift]: %s:%d — %s should be %s\n",
                 file, NR, "\047" variant "\047", "\047" canon "\047"
          rc = 1
        }
        # Continue scanning after this hit.
        stripped = substr(stripped, n + length(variant))
        n = index(stripped, variant)
      }
    }
    END { exit rc }
  ' "$file"
  return $?
}

for canon in "${!variant_map[@]}"; do
  IFS='|' read -ra variants <<< "${variant_map[$canon]}"
  for variant in "${variants[@]}"; do
    for file in "${prose_files[@]}"; do
      [[ "$file" == "$GLOSSARY" ]] && continue
      scan_variant_in_file "$file" "$variant" "$canon" || failed=1
    done
  done
done

# --- Check 4: new-term gate (warning-level pre-MVP-sweep) ---
#
# Identify bolded terms in changed docs that have no glossary entry
# and look load-bearing. We use a conservative heuristic: a token
# bolded as `**hub session**`-style multi-word lowercase phrase is
# a likely candidate. Skip single-word terms (too noisy) and skip
# obviously-non-project content (markdown emphasis on "important",
# etc.) via a small stoplist.
#
# At MVP scale this stays as WARN — the existing doc corpus has
# enough load-bearing terms that the lint would otherwise fail
# every PR until the retroactive sweep clears.

if command -v git >/dev/null 2>&1 && git rev-parse --git-dir >/dev/null 2>&1; then
  # Only inspect docs/ files changed against main. On main itself
  # this picks up nothing — the gate is a PR-time concern.
  base_ref="origin/main"
  if ! git rev-parse "$base_ref" >/dev/null 2>&1; then
    base_ref="main"
  fi
  changed_docs=()
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    [[ "$f" =~ ^docs/.*\.md$ ]] || continue
    [[ "$f" =~ ^docs/(archive|screens|logo)/ ]] && continue
    changed_docs+=("$f")
  done < <(git diff --name-only "$base_ref"...HEAD 2>/dev/null || true)

  # Stoplist: common emphasis tokens that aren't project terms.
  stoplist="^(important|note|warning|todo|tldr|mvp|api|cli|ui|why|how|what|the|when|where)$"

  for f in "${changed_docs[@]}"; do
    while IFS= read -r match; do
      [[ -z "$match" ]] && continue
      term="${match//\*\*/}"
      # Multi-word check (must contain a space).
      [[ "$term" != *" "* ]] && continue
      # Lowercase-only check.
      [[ "$term" =~ [A-Z] ]] && continue
      # Stoplist.
      if [[ "$term" =~ $stoplist ]]; then continue; fi
      # Already in glossary?
      if [[ -n "${canon_terms[$term]+x}" ]]; then continue; fi
      echo "WARN [missing-glossary-entry]: $f — '$term' is bolded but not in glossary; consider adding"
      warned=$((warned + 1))
    done < <(grep -oE '\*\*[a-z][a-z _-]+[a-z]\*\*' "$f" 2>/dev/null | sort -u || true)
  done
fi

if [[ $warned -gt 0 ]]; then
  echo "lint-glossary: $warned warning(s) (non-blocking; will gate post-sweep)"
fi

if [[ $failed -ne 0 ]]; then
  echo "lint-glossary: failed"
  exit 1
fi

echo "lint-glossary: clean"
exit 0
