package resumerecipes

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The parity fixture. Generated from the real table by this test and compared
// byte-for-byte on every run, so the file going stale IS the event "the two
// implementations may now disagree" — the recipe from vision-parity L2 (#526).
//
// Why it exists: N1's declared consumer is the desktop Companion's local agent
// service (vision-parity L3/L4), which runs in Electron main and cannot call
// this package. Without a shared artifact it would re-derive the table in
// TypeScript and drift silently. The TS side reads this file at
//
//	hub/internal/resumerecipes/testdata/resume_recipes_fixture.json
//
// (relative to the repo root) exactly as compareRuns.test.ts already reads the
// config-diff fixture.
//
// Regenerate with:
//
//	go test ./internal/resumerecipes/ -run Fixture -update-resume-fixture
var updateFixture = flag.Bool("update-resume-fixture", false,
	"rewrite testdata/resume_recipes_fixture.json from the current table")

const fixturePath = "testdata/resume_recipes_fixture.json"

type fixture struct {
	Note        string             `json:"note"`
	Version     int                `json:"version"`
	EngineArgv  []fixtureEngineRow `json:"engine_argv"`
	FamilyPlans []fixtureFamilyRow `json:"family_plans"`
	RefChecks   []fixtureRefRow    `json:"session_ref_validation"`
	ShellQuotes []fixtureQuoteRow  `json:"shell_quote"`
}

type fixtureEngineRow struct {
	Engine   string   `json:"engine"`
	Bin      string   `json:"bin"`
	GOOS     string   `json:"goos"`
	RefKind  string   `json:"ref_kind"`
	RefValue string   `json:"ref_value"`
	Argv     []string `json:"argv,omitempty"`
	Error    string   `json:"error,omitempty"`
	Verified string   `json:"verified"`
}

type fixtureFamilyRow struct {
	Family    string   `json:"family"`
	Mechanism string   `json:"mechanism"`
	RefKind   string   `json:"ref_kind"`
	RefValue  string   `json:"ref_value"`
	Engine    string   `json:"engine,omitempty"`
	Argv      []string `json:"argv,omitempty"`
	DedupeKey string   `json:"dedupe_key,omitempty"`
	Error     string   `json:"error,omitempty"`
}

type fixtureRefRow struct {
	Kind  string `json:"kind"`
	Value string `json:"value"`
	Valid bool   `json:"valid"`
	Why   string `json:"why"`
}

type fixtureQuoteRow struct {
	Input  string `json:"input"`
	Output string `json:"output"`
	Why    string `json:"why"`
}

func TestResumeRecipeFixtureIsCurrent(t *testing.T) {
	got, err := buildFixture()
	if err != nil {
		t.Fatalf("build fixture: %v", err)
	}
	if *updateFixture {
		if err := os.MkdirAll(filepath.Dir(fixturePath), 0o755); err != nil {
			t.Fatalf("mkdir testdata: %v", err)
		}
		if err := os.WriteFile(fixturePath, got, 0o644); err != nil {
			t.Fatalf("write fixture: %v", err)
		}
		t.Logf("wrote %s (%d bytes)", fixturePath, len(got))
		return
	}
	want, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("read %s: %v (regenerate with -update-resume-fixture)", fixturePath, err)
	}
	if !bytes.Equal(bytes.TrimSpace(got), bytes.TrimSpace(want)) {
		t.Errorf("%s is stale — the table changed, so any TypeScript reader pinned to "+
			"this file now disagrees with Go. Regenerate with:\n"+
			"  go test ./internal/resumerecipes/ -run Fixture -update-resume-fixture",
			fixturePath)
	}
}

// TestFixtureIsPureASCII keeps the shared artifact readable byte-identically
// from any toolchain: non-ASCII is emitted as \uXXXX escapes rather than raw
// UTF-8, so a reader that mishandles encoding fails loudly instead of subtly.
func TestFixtureIsPureASCII(t *testing.T) {
	data, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	for i, b := range data {
		if b > 0x7f {
			t.Fatalf("byte %d is non-ASCII (0x%02x); the generator must \\u-escape it", i, b)
		}
	}
}

func buildFixture() ([]byte, error) {
	tbl, err := Load()
	if err != nil {
		return nil, err
	}
	f := fixture{
		Note: "Generated by hub/internal/resumerecipes fixture_test.go from recipes.yaml. " +
			"Read by the Go loader's own test and by the desktop Companion's local agent " +
			"service (vision-parity L3/L4) so both languages answer identically. " +
			"Do not hand-edit: regenerate with `go test ./internal/resumerecipes/ " +
			"-run Fixture -update-resume-fixture`.",
		Version: tbl.Version,
	}

	// One row per engine per platform, so a reader that ignores windows_bin is
	// caught by the fixture rather than at a user's terminal.
	for _, e := range tbl.Engines {
		for _, goos := range []string{"linux", "windows"} {
			for _, kind := range []string{RefID, RefPath} {
				value := "SESSION"
				if kind == RefPath {
					value = "/abs/session.jsonl"
				}
				row := fixtureEngineRow{
					Engine: e.Engine, Bin: e.BinFor(goos), GOOS: goos,
					RefKind: kind, RefValue: value, Verified: e.Verified,
				}
				argv, err := e.Argv(SessionRef{Kind: kind, Value: value}, goos)
				if err != nil {
					row.Error = classifyErr(err)
				} else {
					row.Argv = argv
				}
				f.EngineArgv = append(f.EngineArgv, row)
			}
		}
	}

	for _, fam := range tbl.Families {
		row := fixtureFamilyRow{
			Family: fam.Family, Mechanism: fam.Mechanism,
			RefKind: RefID, RefValue: "abc-123",
		}
		p, err := tbl.PlanForFamily(fam.Family, SessionRef{Kind: RefID, Value: "abc-123"}, "linux")
		if err != nil {
			row.Error = classifyErr(err)
		} else {
			row.Engine, row.Argv, row.DedupeKey = p.Engine, p.Argv, p.DedupeKey
		}
		f.FamilyPlans = append(f.FamilyPlans, row)
	}

	// Validation envelope. The boundary cases are where two languages diverge:
	// length is counted in BYTES here, which a JS reader using String.length
	// (UTF-16 units) gets wrong for any non-ASCII id — hence the pair below.
	refCases := []struct {
		kind, value, why string
	}{
		{RefID, "abc-123", "ordinary id"},
		{RefID, "", "empty"},
		{RefID, strings.Repeat("x", MaxSessionIDLen), "exactly the byte limit"},
		{RefID, strings.Repeat("x", MaxSessionIDLen+1), "one byte over the limit"},
		{RefID, "a\nb", "control character (newline)"},
		{RefID, "a\x00b", "control character (NUL)"},
		{RefID, "a\x1bb", "control character (ESC)"},
		{RefID, "café", "non-ASCII: 5 bytes but 4 JS string units"},
		{RefID, strings.Repeat("é", MaxSessionIDLen/2), "non-ASCII exactly at the byte limit"},
		{RefID, strings.Repeat("é", MaxSessionIDLen/2+1), "non-ASCII one char over the byte limit"},
		{RefPath, "/abs/session.jsonl", "absolute path"},
		{RefPath, "relative.jsonl", "not absolute"},
		{RefPath, "", "empty"},
	}
	for _, c := range refCases {
		var err error
		if c.kind == RefID {
			_, err = NewID(c.value)
		} else {
			_, err = NewPath(c.value)
		}
		f.RefChecks = append(f.RefChecks, fixtureRefRow{
			Kind: c.kind, Value: c.value, Valid: err == nil, Why: c.why,
		})
	}

	// Shell quoting. The hub splices these into a backend.cmd that tmux runs
	// through a shell; a TS reader building the same command must agree
	// character for character or it reintroduces the injection.
	quoteCases := []struct{ in, why string }{
		{"abc-123", "ordinary id: unquoted, byte-identical to pre-table behaviour"},
		{"550e8400-e29b-41d4-a716-446655440000", "uuid: unquoted"},
		{"/abs/session.jsonl", "path characters are in the safe set"},
		{"", "empty becomes an explicit empty word"},
		{"abc; rm -rf /", "command separator"},
		{"$(touch /tmp/x)", "command substitution"},
		{"`id`", "backtick substitution"},
		{"a && curl x | sh", "operators and a pipe"},
		{"a'b", "embedded single quote: the four-character splice"},
		{"a\"b", "embedded double quote"},
		{"* ~ ?", "glob and tilde"},
		{"café", "non-ASCII is outside the safe set, so it quotes"},
	}
	for _, c := range quoteCases {
		f.ShellQuotes = append(f.ShellQuotes, fixtureQuoteRow{
			Input: c.in, Output: ShellQuote(c.in), Why: c.why,
		})
	}

	raw, err := json.MarshalIndent(f, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(escapeNonASCII(raw), '\n'), nil
}

// classifyErr maps sentinel errors to stable machine-readable tokens, so the
// fixture records WHICH refusal happened rather than an error string a
// reformat could churn.
func classifyErr(err error) string {
	switch {
	case errors.Is(err, ErrUnknownFamily):
		return "unknown_family"
	case errors.Is(err, ErrNotArgvResume):
		return "not_argv_resume"
	case errors.Is(err, ErrUnsupportedRef):
		return "unsupported_ref_kind"
	default:
		return "error"
	}
}

// escapeNonASCII rewrites every byte above 0x7f as a \uXXXX escape. Go's json
// encoder emits raw UTF-8, which is valid JSON but makes the shared file's
// bytes depend on the reader's encoding handling.
func escapeNonASCII(b []byte) []byte {
	var out bytes.Buffer
	for _, r := range string(b) {
		if r < 0x80 {
			out.WriteRune(r)
			continue
		}
		for _, u := range utf16Units(r) {
			fmt.Fprintf(&out, "\\u%04x", u)
		}
	}
	return out.Bytes()
}

// utf16Units returns the UTF-16 code units for a rune — one for the BMP, a
// surrogate pair above it. JSON's \u escape is defined in UTF-16.
func utf16Units(r rune) []uint16 {
	if r < 0x10000 {
		return []uint16{uint16(r)}
	}
	r -= 0x10000
	return []uint16{uint16(0xd800 + (r >> 10)), uint16(0xdc00 + (r & 0x3ff))}
}
